name: "🐛 Bug Report"
description: "Report an issue with functionality or unexpected behavior"
body:
  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual Behavior"
      description: "What happened, and why it was wrong."
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "What you expected to happen instead, and why."
    validations:
      required: true
  - type: textarea
    id: additional_info
    attributes:
      label: "Additional information about the issue"
      description: "Provide some additional information such as environment, reproducible examples etc."
