name: "💡 Feature Request"
description: "Suggest a new feature or an idea"
body:
  - type: textarea
    id: what
    attributes:
      label: "What is needed?"
      description: "A summary of what you'd like to see added or changed."
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: "Why is this needed?"
      description: "A quick sales pitch for why this feature or idea is needed/valuable."
    validations:
      required: true
  - type: textarea
    id: how
    attributes:
      label: "How can this be done?"
      description: "Provide some ideas on how we can achieve this, examples, resources etc. that can help progress the work."
